name: Scan

on:
  workflow_dispatch

jobs:
  scan:
    permissions:
      security-events: write
      contents: read
      id-token: write
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: | 
         3.1.x
         5.0.x
    - name: Restore .NET
      run: dotnet restore
    - name: Run endorctl
      uses: endorlabs/github-action@5e16037fd8a53f19978a83f2e0ad41090086fae8
      with:
        namespace: "demo"
        api: "https://api.staging.endorlabs.com"
        enable_github_action_token: "true"
        sarif_file: findings.sarif
    - name: Upload SARIF to github
      uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
      with:
        sarif_file: findings.sarif
